<a href="https://colab.research.google.com/github/offmannn/tinkerhub-pytorch-task/blob/master/daily_task/Ranjith/Ranjith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
q=np.random.rand(5,3)
print(q)
w=np.random.rand(3,4)
print(w)

[[0.65072886 0.22845178 0.37238782]
 [0.02598699 0.2367949  0.32273151]
 [0.89165286 0.87121422 0.42468716]
 [0.53881627 0.73737358 0.39073533]
 [0.0239398  0.25109741 0.79745952]]
[[0.19169847 0.06496339 0.05681413 0.06623118]
 [0.23049396 0.48585222 0.14580906 0.70743965]
 [0.69193729 0.12576003 0.02682567 0.65850077]]


In [0]:
e=torch.from_numpy(q)
e.mul_(0);e.add_(2)
print(e)
print(q)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [0]:
r=torch.tensor(w)
r.mul_(0);r.add_(2)
print(r)
print(w)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)
[[0.19169847 0.06496339 0.05681413 0.06623118]
 [0.23049396 0.48585222 0.14580906 0.70743965]
 [0.69193729 0.12576003 0.02682567 0.65850077]]


In [0]:
y=np.matmul(q,r)
y

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], dtype=torch.float64)

In [0]:
z=torch.matmul(e,r)
z

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], dtype=torch.float64)

In [0]:
type(r)

torch.Tensor

In [0]:
type(q)

numpy.ndarray